### ISSUE TITLE
TypeError: object is not a function

### ISSUE THREAD

**Issue by terryx** [nmn/react-infinity#7]
Do you have an example on how to get this working ?
I ran into problem where I set data
```
//this.state.messages = [
{
    "id": 1,
    "title": "heading 1",
    "content": "abc"
  },
{
    "id": 2,
    "title": "heading 2",
    "content": "abcde"
  }
]
<Infinite data={this.state.messages} elementWidth={300} elementHeight={300} />
```

**Comment by nmn** [comment]
Hi, looks like you're missing a few required props:
margin, you could just set this to zero
childComponent: This is a React Class that will be used to actually render the data you are passing.

Try this:

```
var Child = React.createClass({
  render: function(){
    return (
      <div style={{width: 300, height: 300}}>
        <h1>{this.props.title}</h1>
        <p>{this.props.content}</p>
      </div>
    )
  }
})

<Infinite data={this.state.messages}
              elementWidth={300}
              elementHeight={300} 
              margin={0}
              childComponent={React.createFactory(Child)}
              />
```

Let me know if that still doesn't work. I'm mostly working on 2.0 now, but I'll do bug-fixes.

**Comment by terryx** [comment]
Thanks ! it is working but I have 2 problems
1) The `Infinite` component have inaccurate container height making the element not scrollable, to workaround this, I have to specify `style` height to its parent div
2) Key default to `id` for childComponent, what if I have want to create custom key object, for example instead of id, someone use ID

**Comment by nmn** [comment]
@terryx Would love some extra info on 1)
I've been using this version of the library on scribbler.co and the height calculations work fine for me. Is the number off by a little or a lot?

2) it currently uses id, which isn't great. I'll do a patch update to allow you to use custom keys.

**Comment by terryx** [comment]
strange.. i guess is css issue
```javascript
<div className="list">
  <Infinite />
</div>
```

```css
.list {
 height: 100%;
 overflow: hidden;
}
```

it would work if I set css to some value such as `400px` or using js to calculate document height and pass it to inline style

**Comment by nmn** [comment]
@terryx Ok, I think I know the problem. Try using 
```
.list {
 height: 100vh;
 overflow: auto;
}
```

tell me if that works.

The Infinite component will usually create a single wrapper div that has all the child components in it. The container div is sized by javascript after calculating the required height based on the number and size of the children.

If it still doesn't work, please show me a larger code example or something, so I can help debug this.

**Comment by terryx** [comment]
This works, which is same as having js to set height like
`<div className="list" style={style}>`

**Comment by nmn** [comment]
Ok, the issue was a CSS issue, where height 100% doesn't work reliably. Happy to know that everything works now.
